config/routes.rb
Rails.application.routes.draw do
  resources :laps
  resources :pilots

  post '/upload_result', to: 'laps#upload_result'
  root 'laps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :pilot

  def lap_time_string
    Lap.time_formatted(self.lap_time)
  end

  def total_time
    result = Lap.where(pilot_id: self.pilot_id).sum(&:lap_time)
    Lap.time_formatted(result)
  end

  def self.time_formatted(time)
    milliseconds = time % (60000) 
    seconds = milliseconds / 1000
    milliseconds = milliseconds % 1000
    minutes = time / 60000
    minutes.to_s + ':' + seconds.to_s.rjust(2,'0') + '.' + milliseconds.to_s.rjust(3,'0')
  end
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :laps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  before_action :set_lap, only: [:show, :edit, :update, :destroy]

  # GET /laps
  # GET /laps.json
  def index
    service = select_service
    @laps = service.fetch
  end

  # GET /laps/1
  # GET /laps/1.json
  def show
  end

  # GET /laps/new
  def new
    @lap = Lap.new
  end

  # GET /laps/1/edit
  def edit
  end

  def upload_result
    file_path = params[:lap][:race_log].path
    Lap.delete_all
    Pilot.delete_all
    LeitorLog.new(file_path).execute
    redirect_to '/'
  end

  # POST /laps
  # POST /laps.json
  def create
    @lap = Lap.new(lap_params)

    respond_to do |format|
      if @lap.save
        format.html { redirect_to @lap, notice: 'Lap was successfully created.' }
        format.json { render :show, status: :created, location: @lap }
      else
        format.html { render :new }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laps/1
  # PATCH/PUT /laps/1.json
  def update
    respond_to do |format|
      if @lap.update(lap_params)
        format.html { redirect_to @lap, notice: 'Lap was successfully updated.' }
        format.json { render :show, status: :ok, location: @lap }
      else
        format.html { render :edit }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laps/1
  # DELETE /laps/1.json
  def destroy
    @lap.destroy
    respond_to do |format|
      format.html { redirect_to laps_url, notice: 'Lap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lap
      @lap = Lap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lap_params
      params.permit(:race_log)
    end

    def select_service
      @title = 'Voltas'
      if params[:type]=='result'
        @title = 'Resultado'
        return Laps::RaceResultService.new 
      end
      return Laps::LapsService.new
    end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: [:show, :edit, :update, :destroy]

  # GET /pilots
  # GET /pilots.json
  def index
    @pilots = Pilot.all
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: 'Pilot was successfully created.' }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1
  # PATCH/PUT /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: 'Pilot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pilot_params
      params.require(:pilot).permit(:number, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/application/_menu_voltas.slim
ul#voltas.dropdown-content style="width: 300px !important"
  li
    = link_to "Todas as voltas", laps_path
  li
    = link_to "Resultado", laps_path(type: 'result')

app/views/application/_title.slim
nav
  .nav-wrapper.blue.darken-2
    a.brand-logo href="#"  Gympass Test
    ul#nav-mobile.right.hide-on-med-and-down      
      li
        = link_to "Pilotos", pilots_path
      li
        = link_to "Voltas", laps_path
      li
        = link_to "Resultado", laps_path(type:'result')

  

app/views/laps/_form.html.slim
h5 Enviar novo resultado
br
= form_for Lap.new, url: upload_result_path do |f|
  = f.file_field  :race_log
  br
  br
  = f.submit 'Enviar', class: 'btn'
  

app/views/laps/_grid.slim
table.table-striped.table-highlight.responsive-table.centered
  thead
    tr
      th Piloto
      th Tempo total
      - if @title=='Resultado'        
        th Total de voltas
        th Melhor volta
      
      - if @title=='Voltas' 
        th Volta #
        th Tempo da volta
      
      th Velocidade média
      th

  tbody
    - @laps.each do |lap|
      tr
        td = link_to lap[:pilot].name, pilot_path(lap[:pilot].id)
        td = lap[:lap_total]
        td = lap[:lap_count]
        td = raw lap[:best_lap] 
        td = lap[:avg_speed].round(3).to_s + ' km/h'

        

app/views/laps/edit.html.slim
h1 Editing lap

== render 'form'

=> link_to 'Show', @lap
'|
=< link_to 'Back', laps_path

app/views/laps/index.html.slim
h4 
  = @title

= render 'grid.slim'

br
hr/

br/
= render 'form.html.slim'

app/views/laps/new.html.slim
h1 New lap

== render 'form'

= link_to 'Back', laps_path

app/views/laps/result.html.slim
h4 Resultado

= render 'grid.slim'

app/views/laps/show.html.slim
p#notice = notice

p
  strong Pilot:
  = @lap.pilot
p
  strong Lap occurrence:
  = @lap.lap_occurrence
p
  strong Lap number:
  = @lap.lap_number
p
  strong Lap time:
  = @lap.lap_time
p
  strong Avg speed:
  = @lap.avg_speed

=> link_to 'Edit', edit_lap_path(@lap)
'|
=< link_to 'Back', laps_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gympass Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
      $(document).ready(function() {$('.dropdown-trigger').dropdown({constrainWidth: false});})
    </script>
  </head>

  <body>
    <%= render 'title.slim'%>
    <%= yield %>
  </body>
</html>

app/views/pilots/_form.html.slim
= form_for @pilot do |f|
  - if @pilot.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pilot.errors.count, "error")} prohibited this pilot from being saved:"
      ul
        - @pilot.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/pilots/edit.html.slim
h1 Editing pilot

== render 'form'

=> link_to 'Show', @pilot
'|
=< link_to 'Back', pilots_path

app/views/pilots/index.html.slim
h4 Lista de pilotos

table
  thead
    tr
      th Numero
      th Nome
      th Voltas
      th
      th

  tbody
    - @pilots.each do |pilot|
      tr
        td = pilot.number
        td = pilot.name
        td = link_to 'Ver', laps_path(pilot_id: pilot.id)
        td = link_to 'Editar', edit_pilot_path(pilot)

br

= link_to 'Novo Piloto', new_pilot_path, class: 'btn'

app/views/pilots/new.html.slim
h1 New pilot

== render 'form'

= link_to 'Back', pilots_path

app/views/pilots/show.html.slim
p#notice = notice

p
  strong Number:
  = @pilot.number
p
  strong Name:
  = @pilot.name

=> link_to 'Edit', edit_pilot_path(@pilot)
'|
=< link_to 'Back', pilots_path